app-config:
  app-name: topic_server
  profile: dev
  graceful-exit-timeout-mills: 30000

nacos-config:
  namespace-id: 3d895d20-1011-4184-9252-d6ea8aeac0b8
  cluster-name: ""
  addresses: 192.168.1.155:8848
  username: sdim_dev_a
  password: 123456ff
  log-level: debug
  log-dir: ./.nacos/topic_server/log
  cache-dir: ./.nacos/topic_server/cache
nacos-center-config:
  # 配置中心
  config:
    cluster-name: ""
    group-name: TOPIC_SRV
    static:
      - name: static-config.yaml
        group-name:
    dynamic:
  #      - name: dynamic-config.yaml
  #        group-name:
  # 注册/发现中心
  registry-discover:
    cluster-name: ""
    group-name: SDIM_RD
    discover-dial-timeout: 2s

log-config:
  level: trace
  log-async-config:
    queue-size: 200
    quantitative-size: 100
    timing: 100ms
    stop-timeout: 3s
    flush-workers: 2
    debug: false
  file-log-config:
    file-path: ./.logs
    max-file-size: 10
    max-backup: 3
    history-days: 7
    compress: true
  tcp-log-writer-config:
    host: 192.168.1.155
    port: 5171
    keep-alive: 120s
    reconnect-max-delay: 10s
    dial-timeout: 2s
    write-timeout: 2s
    must-connected-in-init: true